image: mcr.microsoft.com/dotnet/sdk:10.0

stages:
  - build
  - validate
  - test

build:
  stage: build
  script:
    - dotnet build
  only:
    - merge_requests
    - master

linter:
  stage: validate
  script:
    - dotnet format --verify-no-changes
  only:
    - merge_requests
    - master

unit_test:
  stage: test
  needs:
    - job: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"
      when: always
      allow_failure: false
    - when: never
  script:
    - dotnet test
